### ISSUE TITLE
de-sublevelify the api

### ISSUE THREAD

**Issue by juliangruber** [juliangruber/level-object#1]
from `levelObj(db.sublevel('key')).toJSON()`

to `levelObj(db).toJSON('key')`

cc @deanlandolt

**Comment by juliangruber** [comment]
or to `levelObj(db, 'key').toJSON()`

I prefer the 1st though because there's less object creation.

**Comment by juliangruber** [comment]
maybe we can do both

**Comment by deanlandolt** [comment]
ISTM the first is more general -- you can build the second on top pretty easily.

**Comment by deanlandolt** [comment]
I'm not sure `toJSON` is the right method name though -- you're not building a *serializable* object (which is what toJSON is typically about). ISTM what you're really asking for when you invoke this method is for a range or **view** of the database that you can manipulate independently, analogous to a sublevel, but at a smaller scale.

**Comment by deanlandolt** [comment]
I might have been misunderstanding the example above -- just trying to say that I think we need a way to lift up a subset of the db that represents a specific object interface though -- and *that* API prob shouldn't be `toJSON` (and `toJSON` may be better built on top of *that* API).

**Comment by juliangruber** [comment]
https://github.com/juliangruber/level-object/commit/8ee468bba8b39963d2814ab666763bf78941b4f4
